### PR TITLE
[WIP] dask PSI operator

### PR DESCRIPTION
**Pull request by sjperkins**

### CODE REVIEW

**Comment by sjperkins** [comment]
The compute() calls work, now I need to test whether the do the write thing. I think I'm going to have to work out how to combine them with the prox_21 code, which will also need daskification.

**Comment by sjperkins** [comment]
@landmanbester I've got the dask prox_21 operator running through. Haven't checked the result. Could you please take a look?

**Comment by landmanbester** [comment]
Awesome, thanks. I'll have a look. Maybe it's also time to get the testing framework up and running. Will give that a go this week

**Comment by sjperkins** [comment]
Cool, BTW have done some basic testing that dot+hdot agree between dask and numpy versions

**Comment by landmanbester** [comment]
Awesome, thanks @sjperkins this is really very useful

**Pull request merged**
